
use_frameworks!
platform :ios, '10.0'

target 'kd_study' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    pod 'AFNetworking'
    
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RxDataSources'
#    pod 'PromiseKit'
    pod 'SnapKit'
    pod 'Masonry'

    pod 'pop', '~> 1.0.10'

    pod 'SDWebImage'
    pod 'SDWebImage/GIF'
    
    
  target 'kd_studyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'kd_studyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
