# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform:ios, '8.0'
use_frameworks!

#plugin 'cocoapods-binary'

target 'TestObjC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Masonry'
  pod 'MBProgressHUD'
  pod 'AFNetworking'

end
